#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
set -o pipefail

error_handler() {
   true "\
###########################################################
## chroot script: ERROR detected. Please report this bug! #
###########################################################"

   exit 1
}

## {{ Set up error handler.
if [ "$(type -t error_handler_general)" = "function" ]; then
   ## Function error_handler_general exists (declared in
   ## help-steps/pre). Prefer to use the more feature rich version of the error
   ## handler.
   trap "error_handler_general" ERR
else
   ## Function error_handler_general does not exist. Script
   ## runs standalone outside the build script. Fall back to a simpler error
   ## handler.
   trap "error_handler" ERR
fi
## }}

own_filename="$(basename "$BASH_SOURCE")"
for skip_script in $SKIP_SCRIPTS; do
   if [ "$skip_script" = "$own_filename" ]; then
      true "INFO: Skipping $own_filename, because SKIP_SCRIPTS includes it."
      exit 0
   fi
done
unset skip_script

## Info.
echo "INFO: Logging anon_dist_build_version $anon_dist_build_version to /var/lib/anon-dist/build_version..."

## Sanity test.
if [ "$anon_dist_build_version" = "" ]; then
   echo "ERROR: anon_dist_build_version is empty! Please report this bug!"
   exit 1
fi

## Support re-running the script.
rm --force "/var/lib/anon-dist/build_version"

mkdir --parents /var/lib/anon-dist

## Debugging.
touch "/var/lib/anon-dist/build_version"

## Logging.
echo "$anon_dist_build_version" > "/var/lib/anon-dist/build_version"

## Debugging.
cat "/var/lib/anon-dist/build_version"

## Explicitly "exit 0", so eventually trapped errors can be ignored.
exit 0
